### ISSUE TITLE
Issue with json output

### ISSUE THREAD

**Issue by awjga** [dincarnato/draco#1]
Hi!

Thank you for developing DRACO.
I was looking at the output of DRACO and found that a comma is missing before the header:
"counts"
"coverage"
"preCoverage"

**Comment by dincarnato** [comment]
Hi awjga,

many thanks for pointing this out!
This is a bug that was introduced in the last commit we did on Sunday... it did escape our attention!
Should be fixed now.
Best,

Danny

**Comment by awjga** [comment]
Glad that I could help!
