### ISSUE TITLE
Installation in Mac fails

### ISSUE THREAD

**Issue by rubindg** [dincarnato/draco#10]
Is there any plans to make this software available for Mac users? 

I am trying to install the software in Mac OSX (Ventura 13.5.2) and these are the updates I have tried so far:

Using Brew install all the packages

> brew install openblas
> brew install armadillo
> brew install boost
> brew install dlib
> brew install tbb

The cmake command will now give an error "Could NOT find OpenMP_C" and for this you have to install libomp as suggested here
> https://stackoverflow.com/questions/53337299/error-could-not-find-openmp-c-when-install-lightgbm-on-macos

After this you will get an error that armadillo and openblas cannot be linked. This is solved by updating the cmake command as 
> cmake .. -DCMAKE_BUILD_TYPE=Release -DLINK_TIME_OPTIMIZATIONS=ON -DNATIVE_BUILD=ON -DARMA_NO_WRAPPER=OFF

Now it after executing make command the final errors are
1. /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/deque:314:34: error: invalid application of 'sizeof' to an incomplete type 'results::Transcript'
2. /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/queue:269:5: error: static_assert failed due to requirement 'is_same<results::Transcript, int>::value' ""

Any idea of how to resolve this?

Thank you,
Regards,
Rubin.

**Comment by dincarnato** [comment]
Hi Rubin,

Unfortunately not.
DRACO has been developed and tested only on Linux.
My advice is to install it on a Linux virtual machine.

Cheers,
Danny
