### ISSUE TITLE
Compilation failed if installed in Conda

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/draco#15]

**Comment by dincarnato** [comment]
Hi Lionel,

you are doing it from within conda, but it looks like your CXX compiler is v9.4.0.
I believe that compiler should still work, despite the fact that we force the minimum requirement to GCC 10.
Would you please try to edit line 8 of the `CMakeLists.txt` file and replace it with:

`if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "9")`

then try again?

Best,
Danny

**Comment by dincarnato** [comment]
Lionel,

it also looks like there is something wrong with your environment. The C compiler (gcc) is identified to be v14.2.0, but the c++ compiler (g++) is identified to be v9.4.0, which is not possible, as g++ is part of gcc. It looks like you have two versions of gcc installed in your conda environment, that clash with each other.

**Comment by dincarnato** [comment]
That doesn't make much sense... what happens if, from within conda you do: `g++ --version`?

**Comment by Asperatus22** [comment]
Well.... it seem that installing gcc with conda does not install g++

(Draco) me@mypc:/c/Users/me$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

i install gxx and check again then 
(Draco) me@mypc:/c/Users/me$ g++ --version
g++ (conda-forge gcc 14.2.0-1) 14.2.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

the i re run 
(Draco) me@mypc:/c/Users/me/draco/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DLINK_TIME_OPTIMIZATIONS=ON -DNATIVE_BUILD=ON -DARMA_NO_WRAPPER=ON
CMake Error at CMakeLists.txt:9 (message):
  Insufficient gcc version.  Minimal supported version for GCC is 10.

i delete the build folder, creat the build folder move to build folder and rerun 
and have an otehr error :
-- Found OpenMP: TRUE (found version "4.5")
CMake Error at /home/me/miniforge3/envs/Draco/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

i run : mamba install conda-forge::pkgconfig

delete creat move to build and rerun and an other error :
-- Found PkgConfig: /home/lbigault/miniforge3/envs/Draco/bin/pkg-config (found version "0.29.2")
CMake Warning at CMakeLists.txt:38 (FIND_PACKAGE):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.


-- dlib not found using CMake packages. Trying pkgconfig.
-- Checking for module 'dlib-1'
--   No package 'dlib-1' found
CMake Error at /home/le/miniforge3/envs/Draco/share/cmake-3.30/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - dlib-1

Call Stack (most recent call first):
  /home/me/miniforge3/envs/Draco/share/cmake-3.30/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  CMakeLists.txt:41 (pkg_check_modules)


It look like there is a problem with dlib install via conda ...

**Comment by dincarnato** [comment]
Can you try to install dlib from source? [http://dlib.net/compile.html](url)
Follow: **Using dlib from C++**

**Comment by Asperatus22** [comment]
conda install conda-forge::dlib-cpp

i rerun cmake and it pass
just an other problem with tbb
-- Checking for module 'tbb'
--   No package 'tbb' found

but i  was able to compile and the test goes well

**Comment by Asperatus22** [comment]
For other user here is a yml file to create a functional environement for Draco (need to install draco as describe in readme)
[Env_Draco.yml.txt](https://github.com/user-attachments/files/17494548/Env_Draco.yml.txt)

**Comment by dincarnato** [comment]
Did you manage to get TBB to work now? Did you install it from source?

**Comment by Asperatus22** [comment]
No i did not install tbb from source but from conda.
the idea is to create a portable environment.
I don't know what tbb is for.
i ll use Draco on a server, managed with slurm.
do you think tbb will be necessary?

**Comment by dincarnato** [comment]
Lionel,
I just noticed that you installed TBB, but not the headers (tbb devel).
Please install this: https://anaconda.org/conda-forge/tbb-devel
Then it should work.

Please let me know.
On a separate note: today I will be releasing the new RNAFramework with a new tool, `rf-mmtools`, as per your request, which will enable manipulation (visualization, merging, etc.) of MM files.

Cheers,
Danny

**Comment by Asperatus22** [comment]
Danny,
i install : conda isntall conda-forge::tbb-devel
tbb is detected :)
rerun the cmake and make and all goes well expert for a warning  but without any consequence :
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/me/miniforge3/envs/Draco/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/me/miniforge3/envs/Draco/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:13 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /home/me/miniforge3/envs/Draco/lib/cmake/Boost-1.85.0/BoostConfig.cmake (found suitable version "1.85.0", minimum required is "1.66")
-- Found Armadillo: /home/me/miniforge3/envs/Draco/include (found version "14.0.3")
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found PkgConfig: /home/me/miniforge3/envs/Draco/bin/pkg-config (found version "0.29.2")
-- Checking for module 'tbb'
--   Found tbb, version 2021.13.0
-- Openblas library found: /home/me/miniforge3/envs/Draco/lib/libopenblas.so
-- Configuring done (2.1s)
-- Generating done (0.3s)

[Conda_Draco_OK.yml.txt](https://github.com/user-attachments/files/17504563/Conda_Draco_OK.yml.txt)


Thanks for you help. :)

And thanks for the mmtools, it will be a great help for merging multiple run

Best regards 

Lionel
