### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ajithperera** [dincarnato/draco#16]
I encountered a very strange compilation error.  
My draco dependencies 
gcc /2.2.0
onetbb/2022.0.0
boost/1.82.0
cmake/3.30.5
dlib/19.24.6

Summary of the error message (I can provide a detailed printout if needed) 

dist/apps/draco/1.0.0/src/results/../windows_merger_windows_impl.hpp:82:16:   required from here
/dist/apps/draco/1.0.0/src/results/../het/detail/vec2d_element_builder_rt_build_at.hpp:169:16: internal compiler error: trying to capture ‘this’ in instantiation of generic lambda
  169 |                construction_base_type::
      |                ^~~~~~~~~~~~~~~~~~~~~~

Have you ever seen anything like this?

Regards, Ajith

**Comment by dincarnato** [comment]
Aijth,

do I read correctly "gcc 2.2.0"???

**Comment by ajithperera** [comment]
I am sorry, It should be 12.2.0 (did not notice the typo).

**Comment by dincarnato** [comment]
Hi Ajith,

Unfortunately that seems to be an issue due to a bug in gcc that has only been fixed in gcc 14. You have two possibilities: either use clang >= 10 or gcc 14.

Hope this helps!

Best,
Danny

**Comment by ajithperera** [comment]
Hi Danny: Thank you. I noticed that around 2022 the code compiled correctly with gcc/12.2.0 (issue #6). I am sure there must have been updates. Usually, gcc is very reliable.  I might try to install Clang and see how that goes. 

Thanks again. 
Ajith

**Comment by dincarnato** [comment]
Ajith, we made quite some updates since then.
And yes, gcc is reliable, but that is a well-documented bug, and, at present, it seems they are not gonna back-port the fix to versions < 14.

**Comment by ajithperera** [comment]
Thank you. I will mark this as resolved.
