### ISSUE TITLE
Containerized version

### ISSUE THREAD

**Issue by reklar** [dincarnato/draco#2]
Hi, is there possibility of offering this via a containerized (Docker or singularity) method?  With this and RNAFramework requiring so many dependencies it would seem likely to get much more adoption if there were an easier method for installation.

Note that most HPC centers do not allow for Docker due to security reasons and typically convert containers to singularity instead ... and apps using docker-compose are hard to convert to singularity so while Docker itself is okay, docker-compose should be avoided if at all possible.

**Comment by dincarnato** [comment]
Dear reklar,

thanks for your message. I understand your request, and we are working hard to require less and less dependencies to make RNAFramework work out-of-the-box. Nonetheless, we will consider your suggestion for one of the future releases!

Best,
Danny
