### ISSUE TITLE
kolmogorov_smirnov.cpp:610:27: error: ‘cached_probabilities’ was not declared in this scope

### ISSUE THREAD

**Issue by mcahn** [dincarnato/draco#3]
Hi, I'm attempting to compile Draco and getting a compilation error:

```
/home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp:610:27: error: ‘cached_probabilities’ was not declared in this scope
  610 |     if (auto table_iter = cached_probabilities.find(n);
      |                           ^~~~~~~~~~~~~~~~~~~~
/home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp: In function ‘double kolmogorov_smirnov_critical_value(unsigned int, double)’:
/home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp:623:5: error: forming reference to void
  623 |   }();

```
gcc is the recommended version:

```
gcc --version
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

```

Any help would be greatly appreciated.

-- Matthew Cahn

**Comment by dincarnato** [comment]
Hi Matthew,

I have forwarded the request to Edoardo, the main developer.
In the meantime, could you please try again from scratch using CLang instead?

Many thanks.
Best,

Danny

**Comment by mcahn** [comment]
Hi Danny,

Unfortunately compiling with clang runs into other errors which I haven't been able to resolve:

` Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)`

So if the code could be made to compile with gcc, that would be great.

Matthew

**Comment by dincarnato** [comment]
Hi Matthew,

have you installed libomp-devel?

Danny

**Comment by mcahn** [comment]
There doesn't seem to be a libomp-devel under Red Hat Enterprise LInux 7x.  I installed llvm-toolset-11.0-libomp, which includes:

`/opt/rh/llvm-toolset-11.0/root/usr/lib64/libomp.so`

So I ran cmake like this:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DLINK_TIME_OPTIMIZATIONS=ON -DNATIVE_BUILD=ON -DARMA_NO_WRAPPER=ON -DTBB_INCLUDE_DIRS=/opt/intel/compilers_and_libraries_2018.3.222/linux/tbb/include -DTBB_LIBRARIES=/home/LOCAL/intel/tbb/latest/lib/intel64/gcc4.8 -DOpenMP_C_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument" -DOpenMP_C_LIB_NAMES=/opt/rh/llvm-toolset-11.0/root/usr/lib64/libomp.so`

but my flag settings must be wrong, because I'm getting:

```
CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS
  OpenMP_/opt/rh/llvm-toolset-11.0/root/usr/lib64/libomp.so_LIBRARY)
```

**Comment by dincarnato** [comment]
So, this is puzzling. It seems to be a common issue on RHEL7 with OpenMP.
Here are the 3 most sound solutions I found, and I recommend you to try:

1. Try to compile using GCC 10

2. Compile OpenMP (https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.0.tar.bz2) and let it install into /usr hierarchy

3. Try adding the followings on top of your CMakeLists.txt file:

set(CMAKE_C_COMPILER "/path/to/clang")
set(CMAKE_CXX_COMPILER "/path/to/clang++")
set(OPENMP_LIBRARIES "/path/to/openmp/lib")
set(OPENMP_INCLUDES "/path/to/openmp/include")

**Comment by mcahn** [comment]
Thanks, I was able to build it with gcc 10.  Note that I had to modifiy kolmogorov_smirnov.cpp by adding "#include <map>" after "#include <cstdlib>".  (So that might have fixed the problem with gcc 9, since that seemed to be the cause of the original compile error.)

Note that the instructions say to do "make install", but there is no "install" target in the Makefile.

Best,
Matthew

**Comment by dincarnato** [comment]
Hi Matthew,

Thanks for your feedback. You are right, we will fix this in the instructions.
Happy that you got it to work!

All the best,
Danny

**Comment by dincarnato** [comment]
Matthew,

Out of curiosity, can you please show me the error you were getting with GCC10 before including the "map" header?

Thanks!
Danny

**Comment by mcahn** [comment]
It turns out that the problem was not gcc v9 vs. v10.  It compiles successfully with both versions of gcc.

The fix was to include map.h in kolmogorov_smirnov.cpp as mentioned above.  (I've edited that comment because the "<" and ">" in the include statement caused github to drop some words. Now it reads correctly).

The complete error message was:

```
//home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp: In function ‘double kolmogorov_smirnov_critical_value(unsigned int, double)’:
//home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp:592:21: error: ‘map’ in namespace ‘std’ does not name a template type
  592 |   thread_local std::map<int, std::vector<double>> cached_probabilities;
      |                     ^~~
//home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp:6:1: note: ‘std::map’ is defined in header ‘<map>’; did you forget to ‘#include <map>’?
    5 | #include <cstdlib>
  +++ |+#include <map>
    6 | #include <vector>
//home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp: In lambda function:
//home/LOCAL/src/draco/src/kolmogorov_smirnov.cpp:610:27: error: ‘cached_probabilities’ was not declared in this scope
  610 |     if (auto table_iter = cached_probabilities.find(n);
      |                           ^~~~~~~~~~~~~~~~~~~~

```

**Comment by dincarnato** [comment]
Thanks Matthew, yeah the error was quite explicit :-) 
Thanks a lot for reporting. It's now fixed. I'll close the issue now.

Best,
Danny
