### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by Alruta** [dincarnato/draco#4]
Hello,
I am trying to install and compile DRACO but I am having quite problems when I try to compile it. I have download all the programs he needs but when I compile, something happens with dlib package so i get this error:

cmake .. -DCMAKE_BUILD_TYPE=Release -DLINK_TIME_OPTIMIZATIONS=ON -DNATIVE_BUILD=ON -DARMA_NO_WRAPPER=ON

-- Could NOT find TBB (missing: TBB_INCLUDE_DIRS TBB_LIBRARIES tbbmalloc) 
CMake Error at /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlibConfig.cmake:21 (include):
  include could not find requested file:

    /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlib.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

CMake Error at /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlibConfig.cmake:23 (get_target_property):
  get_target_property() called with non-existent target "dlib::dlib".
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

CMake Error at CMakeLists.txt:12 (target_link_libraries):
  Cannot specify link libraries for target "MY_TARGET_NAME" which is not
  built by this project.

-- Configuring incomplete, errors occurred!
See also "/home/atabaz/draco/build/CMakeFiles/CMakeOutput.log".

It looks like the file dlib.cmake is missed from dlib, the target "dlib::dlib" don't exist and "MY_TARGET_NAME" is not build. 
I have look for all these without results. Have you any idea what can be happening?
I also send the [CMakeLists.txt](https://github.com/dincarnato/draco/files/9150254/CMakeLists.txt) so you can see the lines where it is marked the errors. 

Thanks you very much.

**Comment by dincarnato** [comment]
Dear Alruta,

the error seems to be connected with TBB: "Could NOT find TBB (missing: TBB_INCLUDE_DIRS TBB_LIBRARIES tbbmalloc)".
Have you installed Intel Threading Building Blocks?

Danny

**Comment by dincarnato** [comment]
Have you installed the devel package? You need the headers.

**Comment by Alruta** [comment]
I don't know what is these packages so maybe I didn't install it. I am going to try installing it. It is called Numpy-devel?

**Comment by Alruta** [comment]
I have install it and when I try to compile it with 
cmake .. -DCMAKE_BUILD_TYPE=Release -DLINK_TIME_OPTIMIZATIONS=ON -DNATIVE_BUILD=ON -DARMA_NO_WRAPPER=ON

I get this error, the same that I get before but without the TTB problem.

-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/atabaz/anaconda3/envs/RNAFRAMEWORK/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /home/atabaz/anaconda3/envs/RNAFRAMEWORK/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.66")  
-- Found Armadillo: /home/atabaz/anaconda3/envs/RNAFRAMEWORK/include (found version "11.2.3") 
CMake Error at cmake/Modules/FindTBB.cmake:187 (file):
  file failed to open for reading (No such file or directory):

    /home/atabaz/anaconda3/envs/RNAFRAMEWORK/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


-- Found TBB: /home/atabaz/anaconda3/envs/RNAFRAMEWORK/include (found version ".") found components: tbbmalloc 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.5")  
CMake Error at /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlibConfig.cmake:21 (include):
  include could not find requested file:

    /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlib.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlibConfig.cmake:23 (get_target_property):
  get_target_property() called with non-existent target "dlib::dlib".
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at CMakeLists.txt:12 (target_link_libraries):
  Cannot specify link libraries for target "MY_TARGET_NAME" which is not
  built by this project.


-- Configuring incomplete, errors occurred!
See also "/home/atabaz/draco/build/CMakeFiles/CMakeOutput.log"

**Comment by dincarnato** [comment]
What OS are you on?

**Comment by wvandertoorn** [comment]
Hi, same issue here on Ubuntu. I installed tbb-devel via conda, and also tried the replacement script for FindTBB.cmake.
`-- Could NOT find TBB (missing: TBB_INCLUDE_DIRS TBB_LIBRARIES tbbmalloc)`

**Comment by dincarnato** [comment]
We have mostly tested DRACO on RedHat/Fedora. Can you please try with that? It looks like the cmake file needs to be updated for new versions of TBB. We will work on that and fix it as soon as possible. Thanks for reporting.

**Comment by Alruta** [comment]
I am using Ubuntu. I have just try with the FindTBB.cmake that you send me but I have the same error message. 

CMake Error at cmake/Modules/FindTBB.cmake:187 (file):
  file failed to open for reading (No such file or directory):

    /home/atabaz/anaconda3/envs/RNAFRAMEWORK/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


CMake Error at /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlibConfig.cmake:21 (include):
  include could not find requested file:

    /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlib.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at /home/atabaz/anaconda3/envs/RNAFRAMEWORK/share/dlib/dlibConfig.cmake:23 (get_target_property):
  get_target_property() called with non-existent target "dlib::dlib".
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at CMakeLists.txt:12 (target_link_libraries):
  Cannot specify link libraries for target "MY_TARGET_NAME" which is not
  built by this project.

Should I try to do this on RedHat/Fedora to solve this?

Thnaks for the help

**Comment by Alruta** [comment]
I think I have solve all the errors except this last, any idea about how solve it??
CMake Error at CMakeLists.txt:12 (target_link_libraries):
  Cannot specify link libraries for target "MY_TARGET_NAME" which is not
  built by this project.

Thanks again!

**Comment by Alruta** [comment]
Hi again, 

thanks for that updating. I only remain these error I can't find which should I do to solve it. 

CMake Error at src/CMakeLists.txt:4 (target_link_libraries):
  Cannot specify link libraries for target "MY_TARGET_NAME" which is not
  built by this project.

I would be very grateful if you know what's going wrong. It looks like I should put something instead of MY_TARGET_NAME, but I don't really know what.

Thank you very much.

**Comment by Alruta** [comment]
I finally did the cmake command but now I have this error when I type make -j4. Any idea about how to solve it? Thanks

[  0%] Building CXX object src/CMakeFiles/args_generate.dir/args_generate.cpp.o
In file included from /home/atabaz/draco/src/args_impl.hpp:6:0,
                 from /home/atabaz/draco/src/args_def.hpp:3,
                 from /home/atabaz/draco/src/args_generate.cpp:1:
/home/atabaz/draco/src/cte/string.hpp:5:23: fatal error: string_view: No such file or directory
compilation terminated.
src/CMakeFiles/args_generate.dir/build.make:75: recipe for target 'src/CMakeFiles/args_generate.dir/args_generate.cpp.o' failed
make[2]: *** [src/CMakeFiles/args_generate.dir/args_generate.cpp.o] Error 1
CMakeFiles/Makefile2:192: recipe for target 'src/CMakeFiles/args_generate.dir/all' failed
make[1]: *** [src/CMakeFiles/args_generate.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dincarnato** [comment]
Alruta,

please understand that we are not ignoring you. The developer of DRACO does not work in the lab anymore, so it takes time for him to go through the code and understand the issue and fix it.
Looking at the error you get, I have the feeling you are using an old compiler. What version of GCC (or CLANG) are you using?

**Comment by Alruta** [comment]
For sure, no offense if I keep asking. I just give a little step and I get a different error that I would like to ask. I am very grateful because you are spending your time in helping me.

My GCC version is 12.1 and I get it through conda. I don't know if it can affect.

Thanks again and sorry for my insistence

**Comment by dincarnato** [comment]
Hi both,

we have now updated the cmake file. We have tested it on a fresh Linux install and everything worked fine.
@Alruta I have the feeling your Linux environment might be "screwed up". I suggest you to start with a new environment and to install everything from source.

Best,
Danny

**Comment by Alruta** [comment]
Hi Danny,

Thank you very much for keep working on my issue. That's what I did and the problem was that I was trying to compile DRACO in ubuntu  16.04 and it couldn't manage the gcc version required for DRACO. Now on other machine with ubunto 20.04 I have no problems using it.

Thank you very much!

**Comment by dincarnato** [comment]
Hi Alruta, 

that's great. Happy it fixed.

Best,
Danny
