### ISSUE TITLE
Make step fails at compilation

### ISSUE THREAD

**Issue by aarduprey** [dincarnato/draco#6]
I'm trying to compile drago on an EC2 linux instance (m5a type). cmake works, but the make step fails, returning a lot of errors as shown in the log below (edited to remove the host information for security)

[draco errors.txt](https://github.com/dincarnato/draco/files/9920631/draco.errors.txt)

Draco was cloned from github yesterday

Dependencies installed:
==> gcc: stable 12.2.0 (bottled)
==> cmake: stable 3.24.2 (bottled)
==> openblas: stable 0.3.21 (bottled)
==> armadillo: stable 11.4.2 (bottled)
==> boost: stable 1.80.0 (bottled)
==> dlib: stable 19.24 (bottled)
==> tbb: stable 2021.7.0 (bottled)

**Comment by dincarnato** [comment]
Hi aarduprey,

This is weird, with the same configuration we don't get the error.

Can you please cleanup the build dir and send us also the cmake output?

Tnx,
Danny

**Comment by aarduprey** [comment]
I deleted the build folder, recreated it, placed the cache file (else cmake fails to find armadillo, I had to specify the path manually in the cache), and ran the complilation. Same errors.
[draco errors 2.txt](https://github.com/dincarnato/draco/files/9921275/draco.errors.2.txt)

Here's the build folder after that:
[build.zip](https://github.com/dincarnato/draco/files/9921270/build.zip)

**Comment by dincarnato** [comment]
aarduprey, please carefully look at your cmake output:

-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1

You are definitely not using the right compiler. That's the issue.

Best,
Danny

**Comment by aarduprey** [comment]
Indeed, it was the only issue, and setting those variables before compilation solved the issue

export CC=/home/linuxbrew/.linuxbrew/bin/gcc-12
export CXX=/home/linuxbrew/.linuxbrew/bin/g++-12

I have been able to compile and process the 1conf.mm file.

**Comment by dincarnato** [comment]
Great! Have fun with DRACO :-)
