### ISSUE TITLE
running test file

### ISSUE THREAD

**Issue by wonaya** [dincarnato/draco#7]
Hi again, 

I was using the test dataset by using `draco --mm 1conf.mm`
and here is the output I got. 

```
(base) draco --mm 1conf.mm 

[+] Starting DRACO analysis. This might take a while...
[+] Analyzing transcript RNA_1Aborted
```
Let me know if you have any insights on what bring this error. 
Thanks!

**Comment by dincarnato** [comment]
Dear wonaya,
there is still something wrong with your install of DRACO.
I really cannot say, cause it works smoothly for every machine we configured it on.
My advice is to create a virtual machine with the latest Fedora or Arch, install the requirements, and install it there.
Best,
Danny
